# Generated by Django 5.1.4 on 2024-12-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_driver_license_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="driver",
            new_name="drivers",
        ),
    ]
